apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ADS-Github.comS3
  description: |
    Aplication Lyfecycle Management. Build and run your Apps
  links:
    - title: Website
      url: https://application-lifecycle.factory.orange-business.com
    - title: Documentation
      url: https://documentation.factory.orange-business.com/azdev/user-guide/
  annotations: 
    backstage.io/techdocs-ref: dir:.
spec:
  type: toolS3
  owner: DTFB
  lifecycle: production
